# Generated by Django 4.2.7 on 2024-02-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_id', models.IntegerField()),
                ('name', models.TextField(null=True)),
                ('ip', models.TextField(max_length=32)),
                ('last_flash_time', models.DateTimeField(null=True)),
                ('last_flash_successful', models.BooleanField(default=True)),
                ('last_ping_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ndn_router_ip', models.TextField(default='', null=True)),
            ],
        ),
    ]
