# Generated by Django 4.2.7 on 2023-11-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_id', models.IntegerField()),
                ('name', models.TextField(null=True)),
            ],
        ),
    ]
