# Generated by Django 4.2.7 on 2023-11-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='ip',
            field=models.TextField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
