# Generated by Django 4.2.7 on 2023-11-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_boards_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='last_flash_time',
            field=models.DateTimeField(null=True),
        ),
    ]
