# Generated by Django 4.2.7 on 2023-11-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_boards_last_flash_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='last_flash_successful',
            field=models.BooleanField(default=True),
        ),
    ]
