# Generated by Django 4.2.7 on 2023-11-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_boards_last_flash_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='last_ping_time',
            field=models.DateTimeField(null=True),
        ),
    ]
