# Generated by Django 4.2.7 on 2023-11-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_boards_last_ping_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ndn_router_id', models.TextField(null=True)),
            ],
        ),
    ]
