# Generated by Django 4.2.7 on 2023-11-16 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='ndn_router_id',
            new_name='ndn_router_ip',
        ),
    ]
