name: Build docker image
on:
  push:
    branches:
      - master
      - main

jobs:
  build_container:
    permissions: write-all
    name: "Build docker container"
    runs-on: ubuntu-latest
    # Job is currently disabled
    if: false
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ndnappbachelorthesis
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build container"
        run: |
          docker build . --tag ghcr.io/ndnappbachelorthesis/ndn-management:latest
          docker push ghcr.io/ndnappbachelorthesis/ndn-management:latest

