name: Build docker image
on:
  push:
    branches:
      - master
      - main

jobs:
  build_container:
    name: "Build docker container"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: "Build container"
        run: |
          docker build . --tag ghcr.io/derteufelqwe/ndn-management:latest
          docker push ghcr.io/derteufelqwe/ndn-management:latest
